name: Artifact workflow

on:
  push:
    branches:
    - 'artifact_workflow'
  pull_request:
    branches:
    - 'artifact_workflow'

env:
  ARTIFACT_NAME: myArtifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Upload the artifact
      uses: Orfey95/CloudFromation@master
#       uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .
