name: First action

on:
  push:
    branches:
    - 'log_levels'
jobs:
  OUTPUT:
    name: Output
    runs-on: ubuntu-latest

    steps:
    - name: Log levels
      run: |
        echo "::debug::This is a debug message"
        echo "This is an info message"
        echo "::warning::This is a warning"
        echo "::error::This is an error"
